These are my conkeror configuration file.
(Conkeror is a mozilla based, keyboard oriented and highly programmable web browser.)
There are some dirty but featured hacks here, as well as things that I copied from others.

*** bookmark-manipulate.js :
A command to remove a specified bookmark.

*** history-manipulate.js :
A command to clear history.

*** charset-selection.js
Fix broken charset forcing functionality.

*** invisible-scrollbar.js :
Hind scrollbar.

*** scroll-percentage.js :
Scrolling by an arbitrary percentage.

*** undo-kill-buffer.js :
Undo kill buffer, including buffer history.

*** browser-relationship.js :
Add support for some Chinese version of next/previous links.

*** zoom-width.js :
Zoom pages without changing text size.  This helps deal with pages that do not fit slim horizontal resolution.

*** download-path-history.js :
Combine the parent path in history entries with current filename.

*** check-overwrite.js :
More ways to handle existing file when you want to download.  You can choose to perform 1. Overwrite, 2. Automatically append a number, 3 Re-input the filename.

*** unicode-process.js :
Modified process spawning functions to support unicode arguments.

*** hide-modeline-minibuffer.js
Better handling of modeline/minibuffer autohiding.

*** session-backup-auto-save.js
Because auto-save session file is overwritten at launch, it is easy to loose them.   Now the auto-save is copied at launch to a timestamped backup file, so that you can manually load it in case auto-save itself is corrupted.  Also implements a command to purge all backup files.

*** completion-prefix-suffix.js
Fix broken minibuffer completion suffix handling and common prefix handling.
